stages:
  - prepare
  - lint

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "webide"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_OPEN_MERGE_REQUESTS
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_PROTECTED == "true"

include:
  - project: univention/dist/docker-services
    file:
    - kaniko.yml
    - pre-commit.yml

build pre-commit:
  stage: prepare
  rules:
    - changes:
      - .gitlab-ci/Dockerfile.pre-commit
      - .bandit
      - .black
      - .dockerignore
      - .flake8
      - .pre-commit-config.yaml
  extends: .kaniko
  variables:
    DOCKERFILE_PATH: .gitlab-ci/Dockerfile.pre-commit
    KANIKO_ARGS: --cache=true

run pre-commit:
  stage: lint
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE
    PRE_COMMIT_IMAGE: $IMAGE_TAG
  needs:
    - job: build pre-commit
      optional: true
  extends: .pre-commit
  script:
    - git config --global --add safe.directory /builds/univention/components/kelvin-rest-api-client
    - pre-commit run -a
