stages:
  - prepare
  - lint

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "webide"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_OPEN_MERGE_REQUESTS
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_PROTECTED == "true"

include:
  - project: univention/infrastructure/docker-services
    file:
      - kaniko.yml
      - pre-commit.yml
  - project: univention/dev/tooling/ci-components
    file: fragments/misc.yaml


run_pre_commit:
  stage: lint
  extends: .pre-commit

lint_commit_messages:
  variables:
    HOOK_IDS: "conventional-pre-commit issue-reference"
  stage: lint
  extends: .lint_commit_messages
