# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.7.0
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-no-eval
    -   id: python-no-log-warn
    -   id: python-use-type-annotations
    -   id: rst-backticks
-   repo: https://github.com/Lucas-C/pre-commit-hooks-markup
    rev: v1.0.1
    hooks:
    -   id: rst-linter
        exclude: ^docs/.*.rst$
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.3
    hooks:
    -   id: python-safety-dependencies-check
#-   repo: git://github.com/detailyang/pre-commit-shell
#    rev: v1.0.6
#    hooks:
#    -   id: shell-lint
#        args: [--format=json]
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
    -   id: isort
        entry: isort -c
    -   id: isort
        alias: isort-edit
        stages: [manual]
        entry: isort
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        entry: black --check --diff --config .black
        language_version: python3.8
    -   id: black
        alias: black-edit
        stages: [manual]
        entry: black --config .black
        language_version: python3.8
#-   repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
#    rev: v0.1.0
#    hooks:
#    -   id: dockerfilelint
#        stages: [commit]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
    -   id: bandit
        entry: bandit -x tests
#-   repo: https://github.com/pycqa/pydocstyle
#    rev: 5.0.1
#    hooks:
#    -   id: pydocstyle
default_language_version:
    python: python3.8
