# This workflow will install Python dependencies and run integration tests with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Integration tests

on: [ push, pull_request ]

jobs:
    build:

        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [ "3.7", "3.8", "3.9", "3.10" ]

        steps:
            -   uses: actions/checkout@v2
            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python-version }}
            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip wheel
                    python -m pip install pytest-cov
                    python -m pip install -r requirements.txt -r requirements_dev.txt -r requirements_test.txt
                    python -m pip list
            -   name: Install Python package
                run: python -m pip install .
            -   name: Setup timezone
                run: sudo timedatectl set-timezone Europe/Berlin
            -   name: download LXD container
                run: |
                    wget https://download.software-univention.de/download/tarballs/ucs5.0-1e175-ucsschool5.0v1-kelvin151.SHA256 https://download.software-univention.de/download/tarballs/ucs5.0-1e175-ucsschool5.0v1-kelvin151-metadata.tar.xz https://download.software-univention.de/download/tarballs/ucs5.0-1e175-ucsschool5.0v1-kelvin151.tar.xz
                    sha256sum -c ucs5.0-1e175-ucsschool5.0v1-kelvin151.SHA256
            -   name: start LXD container
                run: |
                    sudo lxd init --auto --storage-backend dir
                    sudo lxc image import ucs5.0-1e175-ucsschool5.0v1-kelvin151-metadata.tar.xz ucs5.0-1e175-ucsschool5.0v1-kelvin151.tar.xz --alias ucs5ucsschool5kelvin
                    sudo lxc launch ucs5ucsschool5kelvin kelvin -c security.privileged=true -c security.nesting=true -c raw.lxc=lxc.apparmor.profile=unconfined
                    sleep 60
                    sudo lxc list
                    sudo lxc exec kelvin -- univention-app shell ucsschool-kelvin-rest-api sh -c 'echo -e "domain uni.dtr\nnameserver 172.17.42.1" > /etc/resolv.conf'
                    sudo lxc exec kelvin -- univention-app shell ucsschool-kelvin-rest-api sh -c 'echo "172.17.42.1 m40.uni.dtr m40" >> /etc/hosts'
                    sudo lxc exec kelvin -- univention-app shell ucsschool-kelvin-rest-api /etc/init.d/ucsschool-kelvin-rest-api restart
                    sleep 15
                    echo "$(sudo grep kelvin /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.leases | cut -d ' ' -f 3)" > IP_UCS
                    cat IP_UCS
                    sed -e "s/10.20.30.40/$(cat IP_UCS)/g" -e "s/dc=example,dc=com/dc=uni,dc=dtr/g" -e "s/s3cr3t/univention/g" tests/test_server_example.yaml > tests/test_server.yaml
            -   name: Test with pytest
                run: pytest -l -v --cov=tests --cov=ucsschool --cov-fail-under=90 --cov-report=term-missing
